### ISSUE TITLE
[epic] optimise parameter search spaces for all models

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#158]
Using available datasets.

Need to think about:
* whether to include more parameters as defaults (often `autoemulate` uses a subset)
* whether to extend/reduce the search space for each model

- [x] #168
- [x] #169
- [x] optimise parameter search spaces for **RBF**
- [x] optimise parameter search spaces for **RandomForest**
- [x] optimise parameter search spaces for **GradientBoosting**
- [x] optimise parameter search spaces for **SupportVectorMachines**
- [x] NeuralNetTorch (MLP) (done by @bryanlimy)
