### ISSUE TITLE
[epic] Improve open-source contribution infrastructure

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/autoemulate#71]
- [x] #79
- [x] #121
- [x] #123
- [x] Improve documentation by:
    - [x] Add installation pages (fixed with #120)
    - [x] Add automatic API docs (fixed with #120)
    - [x] Set up infrastructure for tutorials/worked examples (fixed with #122)

**Comment by mastoffel** [comment]
I'm also wondering whether there are any recommendations for EDI standards in open source software, like for the Contribute.md.

**Comment by kallewesterling** [comment]
> I'm also wondering whether there are any recommendations for EDI standards in open source software, like for the CONTRIBUTE.md.

Curious if there's anything in particular you were thinking of here? If you mean Equity, Diversity, and Inclusion, there was [a report published in 2018](https://dial.global/wp-content/uploads/2018/11/GenderOSS_v10_PDF.pdf) which looked at understanding why women are underrepresented and do not always feel welcome. It recommends looking at creating resources, institutional structures, and agency to empower more women in the community.

They also have some specific recommendations for Open Source Communities, some of which may be more important to us than others:
- Build online peer-support networks for women in open source
- Organise proactive measures to attract diverse talent to the community
- Carry out research to understand what aspects of your community might be alien and uncomfortable
for women
- Create a code of conduct for online speech and behaviour and activities to make new hires feel welcomed and appreciated
- Agree on escalating sanctions for anyone who abuses another community member
- End all abuse and gender-based discrimination in your community

If this is what you were thinking of, the Turing Way has some good examples of files with some code of conduct descriptions that might be helpful for us. It builds on the [Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html), which in turn was adapted from guidelines written by the [Django Project](https://www.djangoproject.com/conduct/enforcement-manual/), which was itself based on the [Ada Initiative template](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports) and the [PyCon 2013 Procedure for Handling Harassment Incidents](https://us.pycon.org/2013/about/code-of-conduct/harassment-incidents/). **You can [find the Turing Way's code of conduct here](https://github.com/the-turing-way/the-turing-way/blob/main/CODE_OF_CONDUCT.md) for reference.**

**Comment by kallewesterling** [comment]
I've edited the issue above to include a code of conduct file as well, which will be helpful!

**Comment by mastoffel** [comment]
This is great and exactly what I was thinking of, thanks @kallewesterling! Would be really good discuss this a bit further.

**Comment by kallewesterling** [comment]
Let's chat a bit at an upcoming sprint planning meeting, perhaps?

**Comment by kallewesterling** [comment]
- [ ] To add to documentation (see #6):
    > the user currently has the responsibility for sampling / experimental design, and autoemulate only does the model fitting
- [ ] To add to the contribution guidelines (see #6):
    > this is an open and ongoing invitation to add more sampling/experimental design strategies

**Comment by kallewesterling** [comment]
To add to the contribution guidelines (see #4):
> Adding "other interesting simulations"
